#
# Encryption commands
#

EDITOR ?= vim

.PHONY: passphrase
passphrase:
	$(eval PASSPHRASE ?= $(shell bash -c '[ -z "$$PASSPHRASE" ] && read -s -p "Password: " pwd && echo $$pwd'))

.PHONY: check-gpg-input
check-gpg-input:
ifndef INPUT
	$(error INPUT is undefined)
endif
ifndef OUTPUT
	$(error OUTPUT is undefined)
endif

.PHONY: gpg-decrypt
gpg-decrypt: passphrase check-gpg-input
	@echo $(PASSPHRASE) | gpg --output $(OUTPUT) --batch --no-tty --yes --passphrase-fd 0 --decrypt $(INPUT)
	@echo ""

.PHONY: gpg-encrypt
gpg-encrypt: passphrase check-gpg-input
	@echo $(PASSPHRASE) | gpg --output $(OUTPUT) --batch --no-tty --yes --passphrase-fd 0 --symmetric $(INPUT)
	@echo ""

.PHONY: gpg-edit
gpg-edit:
ifndef TARGET
	$(error TARGET is undefined)
endif
	$(eval TMPFILE = $(shell mktemp))
	INPUT=$(TARGET) OUTPUT=$(TMPFILE) $(MAKE) -s gpg-decrypt && \
	$(EDITOR) $(TMPFILE) && \
	INPUT=$(TMPFILE) OUTPUT=$(TARGET) $(MAKE) -s gpg-encrypt
	rm -f $(TMPFILE)

