APPLICATION_PATH ?= $(abspath .)
WORKDIR ?=
BUILD_PATH ?= bin
CI_STARTER_KIT_DIR ?= ci-starter-kit

#
# Common for make files commands
#

# Print env variable from Makefile.
# Example:
#   $ cat ./env/default
#   FIRST=1
#   SECOND=3
#   $ cat ./env/staging
#   SECOND=5
# 	$ make combine-env-files INPUT_PRIMARY=env/default INPUT_OVERRIDE=env/staging OUTPUT=env/staging_combined
#   $ cat ./env/staging_combined
#   FIRST=1
#   SECOND=5
.PHONY: combine-env-files
combine-env-files:
	env -i $$(cat ${INPUT_PRIMARY} | xargs) $$(cat ${INPUT_OVERRIDE} | xargs) > ${OUTPUT}

# Print env variable from Makefile.
# Example:
# 	make print-DEIS_APPLICATION_FILTER
# 	> ci-starter-kit
.PHONY: print-%
print-%:
	@echo '$($*)'

include $(APPLICATION_PATH)/$(CI_STARTER_KIT_DIR)/Makefile.docker
ifeq ($(findstring docker-run-deis-v1-client,$(MAKECMDGOALS)),)
	include $(APPLICATION_PATH)/$(CI_STARTER_KIT_DIR)/Makefile.deis
endif
ifeq ($(findstring docker-run-deis-client,$(MAKECMDGOALS)),)
	include $(APPLICATION_PATH)/$(CI_STARTER_KIT_DIR)/Makefile.deis2
endif
include $(APPLICATION_PATH)/$(CI_STARTER_KIT_DIR)/Makefile.encrypt

# Source url: http://stackoverflow.com/questions/2214575/passing-arguments-to-make-run
%:
	@:
