# ================ docker-run-* =================

.PHONY: docker-run-app-install
docker-run-app-install: DOCKER_RUN_ARGS = -i --cidfile=$@_cidfile.txt
docker-run-app-install: DOCKER_RUN_ENV = -e INSTALL_ARGS="$(DOCKER_INSTALL_ARGS)"
docker-run-app-install:
	@rm -f ./$@_cidfile.txt ; \
	$(call run-in-docker,bash -c 'set -ex && \
		rm -rf $(BUILD_PATH) && mkdir $(BUILD_PATH) && \
		make build'); \
	status=$$?; \
	cid=`cat ./$@_cidfile.txt` ; \
	if [ $$status -eq 0 ]; then \
		docker cp --follow-link $${cid}:$(DOCKER_RUN_WORKDIR)/$(BUILD_PATH) .; \
	fi; \
	docker rm -f -v $${cid} &> /dev/null; \
	exit $$status

.PHONY: docker-run-app-test
docker-run-app-test:
	$(call run-in-docker,bash -c "make test")

.PHONY: docker-run-app-lint
docker-run-app-lint:
	$(call run-in-docker,bash -c "make lint")

# ================ docker-build-* =================

.PHONY: docker-build-dev-image
docker-build-dev-image: DOCKER_FILE = Dockerfile.dev
docker-build-dev-image: DOCKER_BUILD_CONTEXT = .
docker-build-dev-image: DOCKER_BUILD_ARG = \
	--build-arg SOURCE_PATH=$(DOCKER_RUN_WORKDIR)
docker-build-dev-image: docker-build

.PHONY: docker-build-prod-image
docker-build-prod-image: DOCKER_FILE = Dockerfile
docker-build-prod-image: DOCKER_BUILD_CONTEXT = .
docker-build-prod-image: DOCKER_BUILD_ARG += \
	--build-arg SOURCE_PATH=$(DOCKER_RUN_WORKDIR) \
	--build-arg BUILD_PATH=$(BUILD_PATH) \
	--build-arg PORT=$(DOCKER_RUN_PORT) \
	--build-arg HEALTHCHECK=$(HEALTHCHECK_PATH)
docker-build-prod-image: docker-build

# ================ docker-app-* =================

.PHONY: docker-app-install
docker-app-install: docker-build-dev-image docker-run-app-install

.PHONY: docker-app-test
docker-app-test: docker-build-dev-image docker-run-app-test

.PHONY: docker-app-lint
docker-app-lint: docker-build-dev-image docker-run-app-lint

.PHONY: docker-app-run
docker-app-run: DOCKER_RUN_ARGS = -it --rm -p $(DOCKER_RUN_PORT):$(DOCKER_RUN_PORT)
docker-app-run: DOCKER_RUN_VOLUMES =
docker-app-run: TAG = latest
docker-app-run:
	$(call run-in-docker,)

.PHONY: docker-app-run-dev
docker-app-run-dev: DOCKER_RUN_ARGS = -i --rm -t -p $(DOCKER_RUN_PORT):$(DOCKER_RUN_PORT)
docker-app-run-dev: docker-build-dev-image
docker-app-run-dev:
	$(call run-in-docker,bash -c "make install run")

