#
# Common for make files commands
#

# Print env variable from Makefile.
# Example:
#   $ cat ./env/default
#   FIRST=1
#   SECOND=3
#   $ cat ./env/staging
#   SECOND=5
# 	$ make combine-env-files INPUT_PRIMARY=env/default INPUT_OVERRIDE=env/staging OUTPUT=env/staging_combined
#   $ cat ./env/staging_combined
#   FIRST=1
#   SECOND=5
.PHONY: combine-env-files
combine-env-files:
	env -i $$(cat ${INPUT_PRIMARY} | xargs) $$(cat ${INPUT_OVERRIDE} | xargs) > ${OUTPUT}

# Print env variable from Makefile.
# Example:
# 	make print-DEIS_APPLICATION_FILTER
# 	> ci-starter-kit
.PHONY: print-%
print-%:
	@echo '$($*)'
